# Generated by Django 4.2 on 2023-05-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_duplicatecart_alter_order_cart"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="duplicatecart",
            table="duplicate_cart",
        ),
    ]
