# Generated by Django 4.2 on 2023-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_duplicatecart_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="duplicatecart",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
