# Generated by Django 4.2 on 2023-06-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.cart"
            ),
        ),
        migrations.DeleteModel(
            name="DuplicateCart",
        ),
    ]
